#pragma once

constexpr auto STARTUP_REGISTER_EXIT_CODE_SUCCESS = 0;
constexpr auto STARTUP_REGISTER_EXIT_CODE_FAILED_UNKNOWN = 1;
constexpr auto STARTUP_REGISTER_EXIT_CODE_FAILED_OPEN_KEY = 2;
constexpr auto STARTUP_REGISTER_EXIT_CODE_FAILED_REGISTER = 3;
constexpr auto STARTUP_REGISTER_EXIT_CODE_FAILED_DELETE = 4;
